---
# The default user and password to connect to the remote hosts.
ansible_user: "usr_ansible"
ansible_password: "{{ lookup('pipe', 'security find-generic-password -a $USER -s {{ ansible_user }} -w') }}"
ansible_become_password: "{{ ansible_password }}"

# The folder that will contain all OpenSSL Certificates.
certificates_path: "/opt/certificates/"

# The regex that will be used to search for folders. If a folder starts with "_", it will be ignored.
certificates_patterns: "['^[^_](.)*$']"

# The file with all the default configuration.
config_file: "config.yml"

# Specify if when creating new files the old ones should be moved to the backup folder.
backup: True

# When backup is true, old files will be moved into this folder.
# Each certificate's folder will contain a backup folder.
backup_folder: "backup"

# Specify if more messages should be displayed during the executions.
debug: True

# The prefix that will be used to identify a secret in the long list of secrets.
certificate_secret_manager_prefix: "ssl."

# The file that will contain the dates of every notification that was sent about a certification expiring date.
notification_file: "notifications.log"

# The file with the instructions to import a certificate.
import_file: "import.yml"
