---
# Specify if more messages should be displayed during the executions.
debug: false

# The file with all the default variables shared by all companies.
context_file: "context.yml"

# The file with the variables that will be used to create a certificate.
config_file: "config.yml"

# The context of the company, which determines which configuration file to load.
company_context: "{{ company_context | default('home') }}"

# The global context file that will be loaded, using company context specific settings.
company_context_file: "context-{{ company_context }}.yml"

# The global config file that will be loaded, using certificate specific settings.
company_config_file: "config-{{ company_context }}.yml"

# The default roles that should be executed if the the user does not provide any.
default_roles_map:
  - "backup"
  - "private_key"
  - "csr"
  - "certificate"
  - "pkcs12"
  - "verify"

# # Role: Requirements:
# # Path where the certificate authority (CA) certificates are stored.
# debian_ca_certificates_path: "/usr/local/share/ca-certificates"
# redhat_ca_certificates_path: "/etc/pki/ca-trust/source/anchors"
