---
# The domain name of the HomeLab.
domain: "homelab"

# Specify if more messages should be displayed during the executions.
debug: true

# The folder that will contain all OpenSSL Certificates.
certificates_path: "/opt/certificates"

# The regex that will be used to search for folders. If a folder starts with "_", it will be ignored.
certificates_patterns: "['^[^_](.)*$']"

# The file with all the default configuration.
config_file: "config.yml"

# Specify if when creating new files the old ones should be moved to the backup folder.
backup: true

# When backup is true, old files will be moved into this folder.
# Each certificate's folder will contain a backup folder.
backup_folder: "backup"

# The prefix that will be used to identify a secret in the long list of secrets.
certificate_secret_manager_prefix: "ssl."

# The file that will contain the dates of every notification that was sent about a certification expiring date.
notification_file: "notifications.log"

# The file with the instructions to import a certificate.
import_file: "import.yml"

# Import Paths.
path_roles_common: "roles/common"
path_common_tasks: "{{ path_roles_common }}/tasks"
path_tasks_debian: "{{ path_common_tasks }}/debian"

# Known_hosts.
path_debian_known_hosts: "{{ path_tasks_debian }}/known_hosts"
path_debian_known_hosts_add: "{{ path_debian_known_hosts }}/add.yml"

# Packages.
path_debian_packages: "{{ path_tasks_debian }}/packages"
path_packages_apt: "{{ path_debian_packages }}/apt.yml"
path_packages_pip: "{{ path_debian_packages }}/pip.yml"

# Passwords.
path_debian_passwords: "{{ path_tasks_debian }}/passwords"
path_debian_passwords_add: "{{ path_debian_passwords }}/add.yml"
path_debian_passwords_get: "{{ path_debian_passwords }}/get.yml"
