---
# Specify if more messages should be displayed during the executions. Defaults to false if not specified.
debug: false

# Domain for certificates. Options: home, homelab. Defaults to home if not specified.
domain_context: "home"

# Environment of the execution. Options: stg, prd. Defaults to prd if not specified.
execution_environment: "prd"

# # The user for Ansible to connect to other servers.
# ansible_user: "{{ lookup('env', 'ANSIBLE_USER') }}"

# # The password for the Ansible user to connect to other servers.
# ansible_password: "{{ lookup('env', 'ANSIBLE_PASSWORD') }}"

# The file with all the default variables shared by all companies.
context_file: "context.yml"

# The global context file that will be loaded, using domain context specific settings.
domain_context_file: "context-{{ domain_context }}.yml"

# The global config file that will be loaded, using certificate specific settings.
domain_config_file: "config-{{ domain_context }}.yml"
