---
### This is just a sample file. Create import files using this one as an example.

# eclipse
eclipse_secret_key: "KEY_STORE_PASSWORD"

# macoskeychain
keychain_path: "/Library/Keychains/System.keychain"
keychain_temp_folder: "/tmp"

# proxmox
proxmox_port: 8006
proxmox_tmp_folder: "/tmp"

# tplinkt1600g
tplink_port: 443
tplink_tftp_folder: "/srv/tftp"
tplink_tftp_app: "tftpd-hpa"

import_config:
  [
    debian_ca:
      [
        { host: "pve-01" },
        { host: "pve-02" },
        { host: "jump-server-core" },
      ],
    eclipse:
      [
        {
          host: "Lucianos-MacBook-Pro.local",
          pkcs12_dest: "/opt/certificates/localhost/localhost.p12",
          secret_file: "/Users/lsampaio/.config/SpringBoot/secret.properties",
          secret_key: "{{ eclipse_secret_key }}",
        },
      ],
    macoskeychain:
      [
        {
          host: "Lucianos-MacBook-Pro.local",
          keychain_path: "{{ keychain_path }}",
          temp_folder: "{{ keychain_temp_folder }}",
        },
      ],
    openssl: [{ host: "Lucianos-MacBook-Pro.local" }],
    proxmox:
      [
        {
          host: "pve-01",
          url: "pve-01.homelab",
          port: "{{ proxmox_port }}",
          tmp_folder: "{{ proxmox_tmp_folder }}",
        },
      ],
    python: [{ host: "Lucianos-MacBook-Pro.local", version: "3" }],
    tplinkt1600g:
      [
        {
          switch_id: "T1600G-28TS",
          host: "switch",
          url: "switch.homelab",
          port: "{{ tplink_port }}",
          tftp_folder: "{{ tplink_tftp_folder }}",
          tftp_app: "{{ tplink_tftp_app }}",
        },
      ],
  ]
