---
### This is just a sample file. Create import files using this one as an example.

# macoskeychain
keychain_path: "/Library/Keychains/System.keychain"
temp_folder: "/tmp"

# eclipse
secret_key: "KEY_STORE_PASSWORD"

import_config: [
  macoskeychain: [
    {
      host: "MacBook-Pro-Luciano.local",
      keychain_path: "{{ keychain_path }}",
      temp_folder: "{{ temp_folder }}"
    },
    {
      host: "MacBook-Pro-Fernanda.local",
      keychain_path: "{{ keychain_path }}",
      temp_folder: "{{ temp_folder }}"
    }
  ],
  eclipse: [
    {
      host: "MacBook-Pro-Luciano.local",
      pkcs12_dest: "/opt/certificates/localhost/localhost.p12",
      secret_file: "/Users/lsampaio/.config/SpringBoot/secret.properties",
      secret_key: "{{ secret_key }}"
    }
  ]
]
