---
- name: Create a PKCS#12 file
  hosts: CertificateAuthorityServer

  tasks:
    - name: Getting the list of certificates
      import_tasks: "roles/certificate/tasks/find-certificates-in-folder.yml"

    - name: Including task to create a PKCS#12 file
      include_tasks: "roles/certificate/tasks/create-pkcs12.yml"
      vars:
        certificate_path: "{{ item }}"
        include_config_files: true
      loop: "{{ certificates_list }}"
