---
- name: Create a certificate signing request (CSR)
  hosts: CertificateAuthorityServer

  tasks:
    - name: Getting the list of certificates
      import_tasks: "roles/certificate/tasks/find-certificates-in-folder.yml"

    - name: Including task to create a certificate signing request (CSR)
      include_tasks: "roles/certificate/tasks/create-signing-request.yml"
      vars:
        certificate_path: "{{ item }}"
        include_config_files: true
      loop: "{{ certificates_list }}"
