---
- name: "Import the certificates where they are used"
  hosts: "CertificateAuthorityServer"
  become: true

  tasks:
    - name: "Getting the list of certificates"
      import_tasks: "roles/certificate/tasks/find-certificates-in-folder.yml"

    - name: "Including task to import the certificate"
      include_tasks: "roles/certificate/tasks/import-certificate.yml"
      vars:
        certificate_path: "{{ item }}"
        include_config_files: true
      loop: "{{ certificates_list }}"
