---
- name: Prepare the Certificate Authority Server
  hosts: CertificateAuthorityServer

  tasks: 
    - name: Installing and upgrading the pip package
      pip:
        name: "pip"
        state: "latest"

    - name: Installing all the required Python packages
      pip:
        name: "{{ item }}"
        state: "latest"
      loop:
        - "cryptography"
        - "pyOpenSSL"
        - "jmespath"
        - "pexpect"

    - name: Creating the folder that will contain all OpenSSL Certificates
      file:
        path: "{{ item }}"
        state: directory
        recurse: yes
      loop: 
        - "{{ certificates_path }}"

    - name: Installing all the required collections
      community.general.ansible_galaxy_install:
        type: "collection"
        name: "{{ item }}"
      loop:
        - "community.crypto"
