---
- import_playbook: "setup_control_machine.yml"
- import_playbook: "create_private_key.yml"
- import_playbook: "create_signing_request.yml"
- import_playbook: "create_certificate.yml"
- import_playbook: "create_pkcs12.yml"
- import_playbook: "verify_certificate.yml"
- import_playbook: "import_certificate.yml"
