---
- name: "Setting up the control machine to run Ansible scripts"
  import_playbook: "control_machine.yml"

- name: "Create a PKCS#12 file"
  import_playbook: "create_pkcs12.yml"

- name: "Verify if the certificate is valid"
  import_playbook: "verify_certificate.yml"

# - name: "Import the certificates where they are used"
#   import_playbook: "import_certificate.yml"
