---
- name: "Verify if the certificate is valid"
  hosts: "CertificateAuthorityServer"

  tasks:
    - name: "Getting the list of certificates"
      ansible.builtin.import_tasks: "roles/certificate/tasks/find-certificates-in-folder.yml"

    - name: "Including task to verify if the certificate is valid"
      ansible.builtin.include_tasks: "roles/certificate/tasks/verify-certificate.yml"
      vars:
        certificate_path: "{{ item }}"
        include_config_files: true
      loop: "{{ certificates_list }}"
