---
# The version of the configuration file format.
version: "2.0"

# Variables that will be used for creating a certificate signing request.
# https://docs.ansible.com/ansible/latest/collections/community/crypto/openssl_csr_module.html
csr:
  # Organization name to be included in the CSR.
  organization_name: "Certificate Authority Homelab"
  # Common name (usually the domain name) to be included in the CSR.
  # This field is often required for SSL/TLS certificates.
  common_name: "ca.lan.home"
  # Subject Alternative Names (SANs) to be included in the CSR.
  # This is a list of additional names (e.g., domain names) the certificate should cover.
  # Example:
  # subject_alt_name:
    # - "DNS:site.lan.home"
    # - "DNS:othersan.lan.home"
  subject_alt_name:
    - "DNS:edge-root-ca.lan.home"
  # Basic constraints to be included in the CSR.
  # 'CA:TRUE' indicates that this certificate can be used to sign other certificates.
  # 'CA:FALSE' indicates that this certificate cannot be used to sign other certificates.
  basic_constraints: "CA:TRUE"
  # Key usage extensions to be included in the CSR (Certificate Signing Request).
  # This defines the allowed cryptographic operations for the key.
  # key_usage:
    # - "digitalSignature" # Allows the key to sign data, often for authentication or integrity.
    # - "keyEncipherment"  # Allows the key to encrypt keys for secure communication.
    # - "keyCertSign"      # Allows the key to sign other certificates (typically for CA certificates).
    # - "nonRepudiation"   # Ensures that a key cannot be denied as having signed a document.
  key_usage:
    - "digitalSignature"
    - "keyEncipherment"
    - "keyCertSign"

# Variables that will be used for creating a certificate.
# https://docs.ansible.com/ansible/latest/collections/community/crypto/x509_certificate_module.html
certificate:
  # Sets the expiration date of the certificate.
  # Can be set using relative times (e.g., "365 days") or a specific date (e.g., "2024-12-31"). If empty, it uses a default duration of the role.
  not_after: "+1095d"
