---
- name: "Updating packages cache"
  ansible.builtin.apt:
    update_cache: true

- name: "Installing required packages"
  ansible.builtin.include_tasks: "{{ path_packages_apt }}"
  vars:
    packages:
      - {name: "sshpass"}
      - {name: "libsecret-tools"}
      - {name: "python-is-python3"}
      - {name: "pipx"} # A tool for installing and managing Python packages.
      - {name: "python3-passlib"} # Required to use bcrypt.
      - {name: "python3-jmespath"} # Required to use bcrypt.
      - {name: "python3-pexpect"} # To enable ansible scripts that use the
      - {name: "python3-openssl"}
      - {name: "python3-cryptography"}
      - {name: "python3-setuptools"}
      - {name: "python3-idna"}

- name: "Injecting passlib in Ansible environment"
  ansible.builtin.include_tasks: "{{ path_packages_pipx }}"
  vars:
    packages:
      - {state: "inject", inject_packages: "passlib", name: "ansible"}
      - {state: "inject", inject_packages: "jmespath", name: "ansible"}

- name: "Ensure Ansible Galaxy collections are installed"
  ansible.builtin.include_tasks: "{{ path_packages_ansible_galaxy }}"
  vars:
    packages:
      - {name: "community.crypto"}
