---
- name: "Updating packages cache"
  ansible.builtin.apt:
    update_cache: true

- name: "Installing required packages"
  ansible.builtin.include_tasks: "{{ path_packages_apt }}"
  vars:
    packages:
      - {name: "pip"}
      - {name: "sshpass"}
      - {name: "libsecret-tools"}

- name: "Installing pip packages"
  ansible.builtin.include_tasks: "{{ path_packages_pip }}"
  vars:
    packages:
      # - {name: "pyOpenSSL==21.0.0"}
      # - {name: "cryptography==3.4.8"}
      - {name: "pyOpenSSL"}
      - {name: "cryptography"}
      - {name: "setuptools"}
      - {name: "idna"}
      - {name: "jmespath"}
      - {name: "pexpect"}

- name: "Installing all the required collections"
  community.general.ansible_galaxy_install:
    type: "collection"
    name: "{{ item }}"
  loop:
    - "community.crypto"
