---
- name: Installing apt packages
  import_tasks: "roles/common/tasks/packages/apt.yml"
  vars:
    packages:
      - { name: "pip" }
      - { name: "sshpass" }
      - { name: "libsecret-tools" }

- name: Installing pip packages
  become: false
  import_tasks: "roles/common/tasks/packages/pip.yml"
  vars:
    packages:
      - { name: "pyOpenSSL==21.0.0" }
      - { name: "cryptography==3.4.8" }
      - { name: "setuptools" }
      - { name: "idna" }
      - { name: "jmespath" }
      - { name: "pexpect" }

- name: Installing all the required collections
  community.general.ansible_galaxy_install:
    type: "collection"
    name: "{{ item }}"
  loop:
    - "community.crypto"
