---
- name: Installing apt packages
  import_tasks: "roles/common/tasks/packages/apt.yml"
  vars:
    packages:
      - { name: "pip" }
      - { name: "sshpass" }

- name: Installing pip packages
  become: false
  import_tasks: "roles/common/tasks/packages/pip.yml"
  vars:
    packages:
      - { name: "cryptography==36.0.2" }
      - { name: "pyOpenSSL" }
      - { name: "jmespath" }
      - { name: "pexpect" }

- name: Installing all the required collections
  community.general.ansible_galaxy_install:
    type: "collection"
    name: "{{ item }}"
  loop:
    - "community.crypto"
