---
- name: Creating .ssh directory
  become: false
  file:
    path: "~/.ssh/"
    state: "directory"

- name: Retrieving the fingerprint of the hosts
  set_fact:
    fingerprints: "{{ fingerprints | default([]) +
      [{ 'name' : host_ip, 'key' : host_key }] +
      [{ 'name' : host_name, 'key' : host_name_key }] }}"
  vars:
    host_ip: "{{ hostvars[item].ansible_host | default('') }}"
    host_key: "{{ lookup('pipe', 'ssh-keyscan -t ecdsa {{ host_ip }}') if (host_ip != '') else '' }}"

    host_name: "{{ item | default('') }}"
    host_name_key: "{{ lookup('pipe', 'ssh-keyscan -t ecdsa {{ host_name }}') if (host_name != '') else '' }}"
  loop: "{{ hosts }}"

- name: Adding the fingerprints of all hosts into the know_hosts file
  include_tasks: "roles/common/tasks/known_hosts/add.yml"
  vars:
    ansible_become: false
  loop: "{{ fingerprints }}"
  loop_control:
    loop_var: "host"
