---
pipx_packages:
  # Personal Development Environment - Ansible tools for infrastructure management.
  - {name: "ansible", install_deps: true}
  - {name: "ansible-lint", install_deps: true}
  - {name: "ansible", state: "inject", include_injected: true, inject_packages: ["cryptography", "jmespath", "hvac", "certifi", "passlib"]}
