---
csr_common_name: "firewall.homelab"
csr_subject_alt_name:
  - "DNS:firewall.homelab"
  - "DNS:firewall-01.homelab"
  - "DNS:firewall-02.homelab"
  - "IP:10.0.3.1"
  - "IP:10.0.3.2"
  - "IP:10.0.3.3"
  - "IP:192.168.0.3"
  - "IP:192.168.0.4"
  - "IP:192.168.0.5"
