---
- name: "Creating the basic variables"
  ansible.builtin.set_fact:
    certificate_file: "{{ certificate_path_and_name ~ '.' ~ config_vars.certificate.extension }}"

- name: "Verifying if {{ certificate_file }} file exists"
  ansible.builtin.stat:
    path: "{{ certificate_file }}"
  register: "file_exists"

- name: "Checking certificate file and its validity"
  when: file_exists.stat.exists | bool
  ansible.builtin.include_tasks: "verify.yml"
