---
- name: "Verifying if {{ certificate_file }} file exists"
  ansible.builtin.stat:
    path: "{{ certificate_file }}"
  register: "file_exists"

- name: "Checking certificate file and its validity"
  when: file_exists.stat.exists | bool
  ansible.builtin.include_tasks: "verify.yml"
