---
- name: "Setting the 'who executed' audit message"
  when: (awx_user_name is defined) # and (certificate_process_mode in ["creating", "importing"])
  ansible.builtin.set_fact:
    who_executed: "{{ awx_user_name }}{{' - ' ~ awx_user_email if (awx_user_email is defined and awx_user_email) else ''}}"

# - name: "Setting email subject for new certificate"
#   when: certificate_process_mode == "creating"
#   ansible.builtin.set_fact:
#     mail_subject: "[SSL] The certificate: {{ certificate_common_name }} was created"
#     mail_main_message: >
#       The certificate '<strong>{{ certificate_common_name }}</strong>' was created
#       using <strong>{{ config_vars.certificate_ca_name | default(config_vars.certificate_signing_provider) }}</strong>.

# - name: "Setting email subject for importing certificate"
#   when: certificate_process_mode == "importing"
#   ansible.builtin.set_fact:
#     mail_subject: "[SSL] The certificate: {{ certificate_common_name }} was imported"
#     mail_main_message: >
#       The certificate '<strong>{{ certificate_common_name }}</strong>' was imported into '<strong>{{ import_type }}</strong>'.

- name: "Setting email subject for certificate nearing expiration (yellow alert)"
  when: certificate_alert_is_yellow
  ansible.builtin.set_fact:
    mail_subject: "[SSL][Attention] - The certificate {{ certificate_common_name }} is expiring in {{ certificate_days_to_expire }} days"
    mail_main_message: >
      The certificate '<strong>{{ certificate_common_name }}</strong>' is expiring in
      <strong style='color: red;'>{{ certificate_days_to_expire }}</strong> days.

- name: "Setting email subject for critical certificate expiration (red alert)"
  when: certificate_alert_is_red
  ansible.builtin.set_fact:
    mail_subject: "[SSL][Alert] - The certificate {{ certificate_common_name }} is expiring in {{ certificate_days_to_expire }} days"
    mail_main_message: >
      The certificate '<strong>{{ certificate_common_name }}</strong>' is expiring in
      <strong style='color: red;'>{{ certificate_days_to_expire }}</strong> days.

- name: "Setting email subject for expired certificate notification"
  when: certificate_info.expired
  ansible.builtin.set_fact:
    mail_subject: "[SSL][Urgent] - The certificate {{ certificate_common_name }} is expired"
    mail_main_message: >
      The certificate '<strong>{{ certificate_common_name }}</strong>' is expired.

- name: "Printing notification variables"
  when: debug | bool
  ansible.builtin.debug:
    msg:
      - "who_executed: {{ who_executed | default('Not defined') }}"
      - "Mail Subject: {{ mail_subject | default('Not defined') }}"
      - "Mail Main Message: {{ mail_main_message | default('Not defined') }}"
