---
# The version of the configuration file format.
version: "2.0"

# Specifies the method used to sign the certificate.
# Options:
# - "openssl": Use the local OpenSSL tool to sign the certificate.
# - "vault": Use HashiCorp Vault to sign the certificate (default).
certificate_signing_method: "vault"

# Variables that will be used for creating a private key.
# https://docs.ansible.com/ansible/latest/collections/community/crypto/openssl_privatekey_module.html
private_key:
  # Extension for the private key file.
  # Common extensions include 'key' or 'pem'.
  extension: "key"

  # Determines which format the private key is written in.
  # By default, PKCS1 (traditional OpenSSL format) is used for all keys which support it.
  # Please note that not every key can be exported in any format.
  # The value "auto" selects a format based on the key format.
  # The value "auto_ignore" does the same, but for existing private key files,
  # it will not force a regenerate when its format is not the automatically selected one for generation.
  # Note that if the format for an existing private key mismatches, the key is regenerated by default.
  # To change this behavior, use the format_mismatch option.
  # Choices: [pkcs1, pkcs8, raw, auto, auto_ignore]
  format: "pkcs8"

  # Type of the private key to be generated.
  # Determines the algorithm used for generating the private key.
  # Common options include:
  # - 'RSA': Widely used and supports various key lengths (e.g., 2048, 4096 bits).
  # - 'DSA': Less commonly used, mainly for compatibility with older systems.
  # - 'ECC': Uses elliptic curve cryptography for smaller key sizes and faster performance.
  # - 'Ed25519': A modern elliptic curve algorithm known for its speed and security.
  type: "ECC"

  # The size of the private key in bits.
  # Common sizes for RSA keys are 2048, 3072, or 4096 bits.
  # Size of the private key in bits.
  # For RSA, 2048 was a standard size, balancing security and performance.
  # To improved security, 3072 is default for RSA type.
  size: 3072

  # For ECC, 256 is a standard size, balancing security and performance.
  # ECC 256 equivalent to 3072 RSA key, use: secp256r1 (default).
  # ECC 384 equivalent to 7680 RSA key, use: secp384r1.
  # ECC 512 equivalent to 10752 RSA key, use: secp512r1.
  curve: "secp256r1"

  # Cipher to be used for encrypting the private key.
  # This defines how the private key will be secured when stored.
  # Common options include:
  # - 'auto': Automatically selects the best available cipher based on OpenSSL defaults.
  # - 'aes256': Uses AES with a 256-bit key for strong encryption.
  # - 'des3': Uses Triple DES for encryption, though it's considered less secure than AES.
  cipher: "auto"

  # Passphrase for the private key file.
  # - An empty string ("") means no passphrase will be used for the private key (default).
  # - A question mark ("?") triggers the automatic generation of a random passphrase.
  # - Any other string (e.g., "SuperSecretPassword") will be used as the explicit passphrase.
  passphrase: "{{ context_vars.passphrase_random_marker }}"

  # Length of the random passphrase if 'passphrase' is set to "?".
  # A size of 30 characters provides strong security for the passphrase.
  passphrase_size: 30

# Variables that will be used for creating a certificate signing request.
# https://docs.ansible.com/ansible/latest/collections/community/crypto/openssl_csr_module.html
csr:
  # Extension for the CSR file.
  # Common extensions include 'csr' or 'pem'.
  extension: "csr"

  # Digest algorithm to be used for signing the CSR (Certificate Signing Request).
  # Determines the hashing algorithm used when creating the CSR.
  # Common options include:
  # - 'sha1': Older and less secure, but still supported for legacy systems.
  # - 'sha256': A strong and widely used digest, considered a secure default.
  # - 'sha512': A stronger alternative to 'sha256', providing even more security.
  digest: "sha256"

  # Country name to be included in the CSR.
  # Use the two-letter ISO 3166-1 country code.
  country_name: "BR"

  # State or province name to be included in the CSR.
  state_or_province_name: "Sergipe"

  # Locality or city name to be included in the CSR.
  locality_name: "Aracaju"

  # Organization name to be included in the CSR.
  organization_name: "TheCodeMaster"

  # Organizational unit name to be included in the CSR.
  organizational_unit_name: "Home"

  # Email address to be included in the CSR.
  email_address: "lsampaioweb+home@gmail.com"

  # Common name (usually the domain name) to be included in the CSR.
  # This field is often required for SSL/TLS certificates.
  common_name: ""

  # Subject Alternative Names (SANs) to be included in the CSR.
  # This is a list of additional names (e.g., domain names) the certificate should cover.
  # Example:
  # subject_alt_name:
    # - "DNS:site.lan.home"
    # - "DNS:othersan.lan.home"
  subject_alt_name: []

  # Basic constraints to be included in the CSR.
  # 'CA:TRUE' indicates that this certificate can be used to sign other certificates.
  # 'CA:FALSE' indicates that this certificate cannot be used to sign other certificates.
  basic_constraints: "CA:FALSE"

  # Indicates whether the basic constraints extension is critical.
  # If true, the extension must be understood and processed by the receiving party.
  basic_constraints_critical: true

  # Key usage extensions to be included in the CSR (Certificate Signing Request).
  # This defines the allowed cryptographic operations for the key.
  key_usage:
    - "digitalSignature" # Allows the key to sign data, often for authentication or integrity.
    - "keyEncipherment"  # Allows the key to encrypt keys for secure communication.
    # - "keyCertSign"      # Allows the key to sign other certificates (typically for CA certificates).
    # - "nonRepudiation"   # Ensures that a key cannot be denied as having signed a document.

  # Indicates whether the key usage extension is critical.
  key_usage_critical: true

  # Extended key usage extensions to be included in the CSR.
  # This further refines the specific purposes of the key in different contexts.
  extended_key_usage:
    - "serverAuth"      # For SSL/TLS server authentication.
    # - "clientAuth"      # For SSL/TLS client authentication.
    # - "emailProtection" # For securing email communications.
    # - "codeSigning"     # For signing executable code to ensure authenticity.
    # - "timeStamping"    # For creating secure timestamps.

  # Indicates whether the extended key usage extension is critical.
  extended_key_usage_critical: true

# Variables that will be used for creating a certificate.
# https://docs.ansible.com/ansible/latest/collections/community/crypto/x509_certificate_module.html
certificate:
  # Extension for the certificate file.
  # Common extensions include 'cer', 'crt', or 'pem'.
  extension: "cer"

  # Digest algorithm to be used for signing self-signed certificates.
  # Determines the hashing algorithm for self-signed certificates.
  # Common options include:
  # - 'sha256': A secure and standard choice for most modern systems.
  # - 'sha512': A stronger alternative for higher security requirements.
  # - If empty, it may default to the system's default digest algorithm.
  digest: "sha256"

  # Sets the expiration date of the certificate.
  # Can be set using relative times (e.g., "365 days") or a specific date (e.g., "2024-12-31"). If empty, it uses a default duration of the role.
  not_after: "+300d"

# Variables that will be used for creating a PKCS12 file.
# https://docs.ansible.com/ansible/latest/collections/community/crypto/openssl_pkcs12_module.html
pkcs12:
  # Extension for the PKCS12 file, which stores both the certificate and its private key.
  # Common extensions include 'p12' or 'pfx'.
  extension: "pfx"

  # Determines the encryption level used.
  # - 'auto' uses the default of the selected backend.
  #   For cryptography, this is what the cryptography library's specific version considers the best available encryption.
  # - 'compatibility2022' uses compatibility settings for older software in 2022.
  #   This is only supported by the cryptography backend if cryptography >= 38.0.0 is available.
  # Choices: [auto,compatibility2022] Default: auto
  encryption: "auto"

  # Action related to the PKCS12 file.
  # 'export' means the certificate and its private key will be exported to a file.
  action: "export"

  # A friendly name for the PKCS12 file, used when importing it into a keystore.
  friendly_name: "Home"

auto_renewal:
  # Enables or disables the auto-renewal feature.
  # When enabled, certificates nearing expiration will be automatically renewed based on the defined criteria.
  enabled: true

  # Number of days before expiration to trigger yellow/warning status.
  days_for_yellow_alert: 15

  # Number of days before expiration to trigger red/critical status.
  days_for_red_alert: 5

  # Number of days before expiration to trigger auto-renewal.
  # If the certificate is set to expire within this number of days, it will be automatically renewed.
  days_before_expiration: 5

  # Maintenance windows for certificate import operations.
  # Each window defines when certificate imports are allowed.
  # Empty list [] means imports allowed at any time.
  certificate_pki_pipeline_window: []
  # Valid day names: monday, tuesday, wednesday, thursday, friday, saturday, sunday.
  # Time format: 'HH:MM' in 24-hour format.
  # Day names are case insensitive (MONDAY, monday, MonDAY all accepted).
  # certificate_pki_pipeline_window:
  #   # Example 1: Weekday evening window.
  #   - days: ["monday", "tuesday", "wednesday", "thursday", "friday"]
  #     start_time: '18:00'  # 6:00 PM time.
  #     end_time: '23:59'    # 11:59 PM time.
  #   # Example 2: Weekend all-day window.
  #   - days: ["saturday", "sunday"]
  #     start_time: '00:00'  # Midnight.
  #     end_time: '23:59'    # 11:59 PM.
  #   # Example 3: Overnight window (crosses midnight).
  #   - days: ["sunday"]     # Sunday night into Monday.
  #     start_time: '23:00'  # 11:00 PM Sunday.
  #     end_time: '06:00'    # 6:00 AM Monday (next day).

# Variables that will be used for sending email notifications about the certificates.
# https://docs.ansible.com/ansible/latest/collections/community/general/mail_module.html
notification_mail:
  # SMTP server settings for sending email notifications.
  host: "smtp.gmail.com"

  # SMTP server port.
  port: 587

  # Type of security to use for the SMTP connection.
  # Options:
  # - "none": No security (not recommended).
  # - "ssl": Use SSL/TLS for the connection.
  # - "starttls": Use STARTTLS to upgrade the connection to a secure one (recommended).
  secure: "starttls"

  # The username for the SMTP server.
  smtp_username: "lsampaioweb@gmail.com"

  # The ID of the SMTP password stored in the Secret Management system.
  smtp_password_id: "certificate-smtp-password"

  # Email details for sending notifications.
  from: "lsampaioweb+home@gmail.com"

  # Recipients of the notification emails.
  to:
    - "lsampaioweb+home@gmail.com"

  # Carbon copy recipients of the notification emails.
  cc: []

  # Format of the email body.
  subtype: "html"
