---
# The version of the configuration file format.
version: "2.0"

# Variables that will be used for creating a private key.
# https://docs.ansible.com/ansible/latest/collections/community/crypto/openssl_privatekey_module.html
private_key:
  # Passphrase for the private key file.
  # - An empty string ("") means no passphrase will be used for the private key (default).
  # - A question mark ("?") triggers the automatic generation of a random passphrase.
  # - Any other string (e.g., "SuperSecretPassword") will be used as the explicit passphrase.
  passphrase: ""

# Variables that will be used for creating a certificate signing request.
# https://docs.ansible.com/ansible/latest/collections/community/crypto/openssl_csr_module.html
csr:
  # Common name (usually the domain name) to be included in the CSR.
  # This field is often required for SSL/TLS certificates.
  common_name: "*.lan.home"
  # Subject Alternative Names (SANs) to be included in the CSR.
  # This is a list of additional names (e.g., domain names) the certificate should cover.
  # Example:
  # subject_alt_name:
    # - "DNS:site.lan.home"
    # - "DNS:othersan.lan.home"
  subject_alt_name:
    - "DNS:*.lan.home"
