---
- name: Joining the elements of the certificates array as a string
  ansible.builtin.set_fact:
    certificates_to_find_patterns: "{{ certificates | join(',') }}"
  when: certificates is defined

- name: Getting the list of certificates in the "{{ certificates_path }}" folder
  ansible.builtin.find:
    paths:
      - "{{ certificates_path }}"
    file_type: "directory"
    use_regex: true
    patterns: "{{ certificates_to_find_patterns | default(certificates_patterns, true) }}"
  register: folders_found

- name: Creating the certificates_list variable
  ansible.builtin.set_fact:
    certificates_list: "{{ folders_found | json_query('files[*].path') }}"

- name: Printing variables
  ansible.builtin.debug:
    var: "certificates_list"
  when: debug | bool
