---
- name: "Trying to retrieve the password of '{{ certificate_secret_manager_prefix }}{{ password_id }}' in order to verify if already exists or it has changed"
  ansible.builtin.command: "secret-tool lookup password {{ certificate_secret_manager_prefix }}{{ password_id }}"
  register: "output"
  failed_when: false
  changed_when: false
  no_log: true
