---
- name: "Creating variables for yellow situation"
  ansible.builtin.set_fact:
    subject: "[Attention] - Certificate expiring in {{ expire_days }} days"
    body_file: "notification-certificate-expiring.j2"
  when: certificate_situation_is_yellow

- name: "Creating variables for red situation"
  ansible.builtin.set_fact:
    subject: "[ALERT] - Certificate expiring in {{ expire_days }} days"
    body_file: "notification-certificate-expiring.j2"
  when: certificate_situation_is_red

- name: "Creating variables for expired situation"
  ansible.builtin.set_fact:
    subject: "[URGENT] - Certificate expired - [URGENT]"
    body_file: "notification-certificate-expired.j2"
  when: certificate_situation_is_expired

- name: "Sending the notification"
  include_tasks: "send-mail-notification.yml"
  when: certificate_situation_is_yellow or certificate_situation_is_red or certificate_situation_is_expired
