---
- name: Trying to retrieve the password of "{{ certificate_secret_manager_prefix }}{{ password_id }}" in order to verify if already exists or it has changed
  import_tasks: "get-password.yml"
  no_log: True

- name: Adding the "{{ password_id }}" password into the Secret Manager
  command: "secret-tool store --label='{{ certificate_secret_manager_prefix }}{{ password_id }}' password {{ certificate_secret_manager_prefix }}{{ password_id }}"
  args:
    stdin: "{{ password }}"
    stdin_add_newline: false
  when: (output.rc == 1 or output.stdout != password)
  no_log: True
