---
- name: Saving the password of the private key in the secret manager with the id "{{ certificate_secret_manager_prefix }}{{ password_id }}"
  command: security add-generic-password -U -a $USER -s "{{ certificate_secret_manager_prefix }}{{ password_id }}" -j "Password for {{ password_id }}" -w "{{ password }}"
