---
- name: Verifying if a previous notification was already sent today
  ansible.builtin.lineinfile:
    path: "{{ certificate_path }}/{{ notification_file }}"
    line: "{{ ansible_date_time.date }}"
    state: "present"
    create: true
    mode: "0644"
  register: "notification_sent"

- name: Sending the email notification
  mail:
    host: "{{ mail_host }}"
    port: "{{ mail_port }}"

    username: "{{ mail_smtp_username | b64decode }}"
    password: "{{ lookup('template', '../templates/get-password-from-secret-manager.j2') }}"

    from: "{{ mail_from | b64decode }}"
    to: "{{ mail_to | b64decode }}"
    cc: "{{ mail_cc | b64decode }}"

    subject: "{{ subject }}"
    subtype: "{{ mail_subtype }}"
    body: "{{ lookup('template', '../templates/'{{ body_file }}) }}"
  vars:
    password_id: "{{ mail_smtp_password_id }}"
  when: notification_sent.changed
