---
- name: Including the dependence to create a private key
  include_tasks: "roles/certificate/tasks/create-private-key.yml"
  vars:
    include_config_files: False
  when: "'privatekey' in dependencies_list"

- name: Including the dependence to create a certificate signing request (CSR)
  include_tasks: "roles/certificate/tasks/create-signing-request.yml"
  vars:
    include_config_files: False
  when: "'certificate-signing-request' in dependencies_list"

- name: Including the dependence to create a certificate
  include_tasks: "roles/certificate/tasks/create-certificate.yml"
  vars:
    include_config_files: False
  when: "'certificate' in dependencies_list"
