---
- name: "Including the dependence to create a private key"
  ansible.builtin.include_tasks: "roles/certificate/tasks/create-private-key.yml"
  vars:
    include_config_files: false
  when: "'privatekey' in dependencies_list"

- name: "Including the dependence to create a certificate signing request (CSR)"
  ansible.builtin.include_tasks: "roles/certificate/tasks/create-signing-request.yml"
  vars:
    include_config_files: false
  when: "'certificate-signing-request' in dependencies_list"

- name: "Including the dependence to create a certificate"
  ansible.builtin.include_tasks: "roles/certificate/tasks/create-certificate.yml"
  vars:
    include_config_files: false
  when: "'certificate' in dependencies_list"
