---
# If the variable is "" (empty), no password will be created for the files.
privatekey_passphrase: ""

csr_common_name: "edge-vault.lan.homelab"
csr_subject_alt_name:
  - "DNS:vault"
  - "DNS:edge-vault.lan.homelab"
