---
# The version of the configuration file format.
version: "2.0"

# Specifies the provider that will be used to sign the certificates.
# Options:
#   "vault": HashiCorp Vault PKI Engine (default).
#   "openssl": The local OpenSSL tool.
certificate_signing_provider: "openssl"

# Secret storage provider for passwords and sensitive data.
# Options:
#   "vault": HashiCorp Vault Secret Engine (default).
#   "keyring" (Ubuntu).
#   "keychain" (MacOS).
secret_provider: "keychain"

# Variables that will be used for creating a certificate signing request.
# https://docs.ansible.com/ansible/latest/collections/community/crypto/openssl_csr_module.html
csr:
  # Common name (usually the domain name) to be included in the CSR.
  # This field is often required for SSL/TLS certificates.
  common_name: "firewall.lan.home"
  # Subject Alternative Names (SANs) to be included in the CSR.
  # This is a list of additional names (e.g., domain names) the certificate should cover.
  # Example:
  # subject_alt_name:
    # - "DNS:site.lan.home"
    # - "DNS:othersan.lan.home"
  subject_alt_name:
    - "DNS:firewall.lan.home"
    - "DNS:firewall-01.lan.home"
