---
# Proxmox requires a private key with no password.
# If the variable is "" (empty), no password will be created for the files.
privatekey_passphrase: ""

csr_common_name: "kvm.homelab"
csr_subject_alt_name:
  - "DNS:kvm.homelab"
  - "DNS:kvm-01.homelab"
  - "DNS:kvm-02.homelab"
  - "DNS:kvm-03.homelab"
  - "DNS:kvm-04.homelab"
  - "DNS:kvm-05.homelab"
  - "DNS:kvm-06.homelab"
  - "DNS:kvm-07.homelab"
