---
# Proxmox requires a private key with no password.
# If the variable is "" (empty), no password will be created for the files.
privatekey_passphrase: ""

csr_common_name: "kvm.homelab"
csr_subject_alt_name:
  - "DNS:kvm.homelab"
  - "DNS:dc-br-se-aju-kvm-01.homelab"
  - "DNS:dc-br-se-aju-kvm-02.homelab"
  - "DNS:dc-br-se-aju-kvm-03.homelab"
  - "DNS:dc-br-se-aju-kvm-04.homelab"
  - "DNS:dc-br-se-aju-kvm-05.homelab"
  - "DNS:dc-br-se-aju-kvm-06.homelab"
  - "DNS:dc-br-se-aju-kvm-07.homelab"
  - "IP:192.168.0.10"
  - "IP:10.0.3.5"
  - "IP:10.0.3.6"
  - "IP:10.0.3.7"
  - "IP:10.0.3.8"
  - "IP:10.0.3.9"
  - "IP:10.0.3.10"
  - "IP:10.0.3.11"
  