---
- name: "Sending the notification email"
  when:
    - mail_subject is defined
    - config_vars.notification_mail.to | length > 0 or config_vars.notification_mail.cc | length > 0
  block:
    - name: "Retrieving SMTP password if not already cached"
      when: smtp_mail_password is not defined or smtp_mail_password | length == 0
      block:
        - name: "Retrieving SMTP password from secret provider: '{{ config_vars.notification_mail.smtp_secret_provider }}'"
          ansible.builtin.include_role:
            name: "common"
            tasks_from: "secrets/{{ config_vars.notification_mail.smtp_secret_provider }}/read.yml"
          vars:
            secret_key: "{{ config_vars.notification_mail.smtp_password_id }}"

        - name: "Setting 'smtp_mail_password' variable from secret value"
          ansible.builtin.set_fact:
            smtp_mail_password: "{{ secret_value | default('', true) }}"

    - name: "Sending email for certificate '{{ certificate_common_name }}' status"
      ansible.builtin.include_role:
        name: "common"
        tasks_from: "mail/send.yml"
      vars:
        mail_host: "{{ config_vars.notification_mail.host }}"
        mail_port: "{{ config_vars.notification_mail.port }}"
        mail_secure: "{{ config_vars.notification_mail.secure }}"
        mail_username: "{{ config_vars.notification_mail.smtp_username }}"
        mail_password: "{{ smtp_mail_password }}"
        mail_from: "{{ config_vars.notification_mail.from }}"
        mail_to: "{{ config_vars.notification_mail.to }}"
        mail_cc: "{{ config_vars.notification_mail.cc }}"
        mail_subtype: "{{ config_vars.notification_mail.subtype }}"
        mail_body_file: "mail-certificate.j2"
