---
# Proxmox requires a private key with no password.
# If the variable is "" (empty), no password will be created for the files.
privatekey_passphrase: ""

csr_common_name: "pve.lan.homelab"
csr_subject_alt_name:
  - "DNS:pve.lan.homelab"
  - "DNS:pve-01.lan.homelab"
  - "DNS:pve-02.lan.homelab"
  - "DNS:pve-03.lan.homelab"
  - "DNS:pve-04.lan.homelab"
  - "DNS:pve-05.lan.homelab"
  - "DNS:pve-06.lan.homelab"
  - "DNS:pve-07.lan.homelab"
  - "IP:172.16.10.3"
  - "IP:172.16.10.4"
  - "IP:172.16.10.5"
  - "IP:172.16.10.6"
  - "IP:172.16.10.7"
  - "IP:172.16.10.8"
  - "IP:172.16.10.9"
