---
- name: Including task to import the certificate into Eclipse application
  include_tasks: "eclipse.yml"
  loop: "{{ import_type.eclipse | default([]) }}"
  loop_control:
    loop_var: host_config
    label: ""
  when: "'eclipse' in import_type"

- name: Including task to import the certificate into the MacOSX keychain
  include_tasks: "macoskeychain.yml"
  loop: "{{ import_type.macoskeychain | default([]) }}"
  loop_control:
    loop_var: host_config
    label: ""
  when: "'macoskeychain' in import_type"

- name: Including task to import the certificate into the cert.pem of OpenSSL
  include_tasks: "openssl.yml"
  loop: "{{ import_type.openssl | default([]) }}"
  loop_control:
    loop_var: host_config
    label: ""
  when: "'openssl' in import_type"

- name: Including task to import the certificate into the Proxmox Hosts
  include_tasks: "proxmox.yml"
  loop: "{{ import_type.proxmox | default([]) }}"
  loop_control:
    loop_var: host_config
    label: ""
  when: "'proxmox' in import_type"

- name: Including task to import the certificate authority into the Proxmox Hosts
  include_tasks: "proxmox-ca.yml"
  loop: "{{ import_type.proxmox_ca | default([]) }}"
  loop_control:
    loop_var: host_config
    label: ""
  when: "'proxmox_ca' in import_type"

- name: Including task to import the certificate into the cert.pem of Python
  include_tasks: "python.yml"
  loop: "{{ import_type.python | default([]) }}"
  loop_control:
    loop_var: host_config
    label: ""
  when: "'python' in import_type"

- name: Including task to import the certificate into the Switch Tplink T1600G-28TS-SG2424
  include_tasks: "tplinkt1600g.yml"
  loop: "{{ import_type.tplinkt1600g | default([]) }}"
  loop_control:
    loop_var: host_config
    label: ""
  when: "'tplinkt1600g' in import_type"
