---
# If the variable is "" (empty), no password will be created for the files.
privatekey_passphrase: ""

csr_common_name: "loadbalancer.homelab"
csr_subject_alt_name:
  - "DNS:loadbalancer.homelab"
  - "DNS:loadbalancer-01.homelab"
  - "DNS:loadbalancer-02.homelab"
