---
- name: "Creating variables for yellow situation"
  when: certificate_alert_is_yellow
  ansible.builtin.set_fact:
    subject: "[Attention] - Certificate expiring in {{ expire_days }} days"
    body_file: "notification-certificate-expiring.j2"

- name: "Creating variables for red situation"
  when: certificate_alert_is_red
  ansible.builtin.set_fact:
    subject: "[ALERT] - Certificate expiring in {{ expire_days }} days"
    body_file: "notification-certificate-expiring.j2"

- name: "Creating variables for expired situation"
  when: certificate_alert_is_expired
  ansible.builtin.set_fact:
    subject: "[URGENT] - Certificate expired - [URGENT]"
    body_file: "notification-certificate-expired.j2"

- name: "Sending the notification"
  when: certificate_alert_is_yellow or certificate_alert_is_red or certificate_alert_is_expired
  ansible.builtin.include_tasks: "send-mail-notification.yml"
